### ISSUE TITLE
Issue with device.currentState.getValue()

### ISSUE THREAD

**Issue by casper-gh** [JZ-SmartThings/SmartThings#2]
Hey it's me Casper from ST forum, I just updated my old code with your new code for 2 devices, a RPi camera and a TV (IR remote on via RPi).

After a few tries, I got the first device working (camera), but when I moved on to the TV (using the same HTTP device handler), I got error `java.lang.NullPointerException: Cannot invoke method getValue() on null object @ line 153`, which is this code:

```
      if (device.currentState("mainswitch").getValue()=="off")
```

It seemed like the value is null, so I had to detach this part `.getValue()`, the trigger went through but the status was incorrect. Then I attached `.getValue()` back, and voila it worked.

I'm not sure it's a bug or just me doing something wrong, just fyi.

**Comment by JZ-SmartThings** [comment]
Just added some NULL checking for that currentstate method. I'm also checking it in. Feel free to give that a shot and give me some feedback. I'll leave this open until I hear some feedback or some huge amount of time passes :) FYI, I also added the same check for the second/custom button. If it still gives you hell, I'll put the NULL check around the currentState and remove the .getvalue() in that portion of the IF statement. Go grab latest groovy driver. Thanks!

```
        if (device.currentState("mainswitch").getValue()==null) {
            FullCommand='MainTriggerOff='
        } else {
            if (device.currentState("mainswitch").getValue()=="off") { FullCommand='MainTriggerOn=' } else { FullCommand='MainTriggerOff=' }
        }
```

**Comment by JZ-SmartThings** [comment]
Changed my mind and now trying a "short-circuit" IF statement which will only do the second part that follows && if the first part succeeds:

```
        if (device.currentState("mainswitch").getValue()==null && device.currentState("mainswitch").getValue()=="off") { FullCommand='MainTriggerOn=' } else { FullCommand='MainTriggerOff=' }
```

**Comment by casper-gh** [comment]
I just add the new validation and got an issue with one of the switch: it kept triggering the OFF command.

Looks like it always falls into the `else` condition.

**Comment by JZ-SmartThings** [comment]
Try with the new logic... turns out that Groovy uses "short circuit" if statements by default which is great. That mean it will NOT go to the next part of the IF check if the first part already failed. Here is the code I modified. Pay attention to the NULL check:

```
    if (DeviceMainMomentary==true) {
        FullCommand='MainTrigger='
    } else {
        if (device.currentState("switch")!=null && device.currentState("switch").getValue()=="off") { FullCommand='MainTriggerOn=' } else { FullCommand='MainTriggerOff=' }
    }
```

and

```
    if (DeviceCustomMomentary==true) {
        FullCommand='CustomTrigger='
    } else {
        log.debug "mainswtich currentState===" + device.currentState("switch")
        if (device.currentState("switch")!=null && device.currentState("customswitch").getValue()=="off") { FullCommand='CustomTriggerOn=' } else { FullCommand='CustomTriggerOff=' }
    }
```

**Comment by casper-gh** [comment]
Thanks for the fix, I just tested and it worked. Let's close it then.
