### ISSUE TITLE
How to use file

### ISSUE THREAD

**Issue by dlevitryon** [JZ-SmartThings/SmartThings#5]
How do I use this file once I got the IRromoteESP8266 working? I could not find it here. https://community.smartthings.com/t/esp8266-nodemcu-arduino-based-tv-remote/50161

I am sorry for a simple question...

**Comment by JZ-SmartThings** [comment]
Honestly I have no idea of what is being asked here. This link you posted does succeed and the instructions are there.

If you're asking "How do I use the SmartThings piece" then that is indeed a confusing topic where you have to create a Device Type/Handler in the SmartThings IDE and then create a new device pointing to that "driver"

Clarify your question and be VERY specific please.

**Comment by JZ-SmartThings** [comment]
No response, closing.
