### ISSUE TITLE
Need some startup help

### ISSUE THREAD

**Issue by Tokn59** [JZ-SmartThings/SmartThings#8]
Hello, not really an issue but I need some startup helkp. I am absolutely new to SmartThings. Had some experience programming the ESP8266 though. Is there any step by step manual available N I created the event handler in Smartthings, created the device etc .. but I am not sure what I nee to configure ? I have already tried these :

input("**192.168.1.240**", "string", title:"Device IP Address", description: "Please enter your device's IP Address", required: true, displayDuringSetup: true)
		input("**80**", "string", title:"Device Port", description: "Empty assumes port 80.", required: false, displayDuringSetup: true)
		input("**http://192.168.1.240/**", "string", title:"URL Path", description: "Rest of the URL, include forward slash.", displayDuringSetup: true)
		input(name: "GET", type: "enum", title: "POST or GET. POST for PHP & GET for Arduino.", options: ["POST","GET"], defaultValue: "POST", required: false, displayDuringSetup: true)

Can you please help me get started ? Thank you so much !!!

**Comment by JZ-SmartThings** [comment]
Do me a favor and ask for assistance on the SmartThings forum. Much easier than GitHub issues, etc.

You likely need to add a new Device Handler on the ST API website, then paste my code. Then create new Device (not Handler) and for the driver/type use the new one that you created (should be at the bottom).

For further help do post on ST forum, please.

**Comment by Tokn59** [comment]
Ok sorry .. I will post it in the forum.  I have created the Device Handler and Device and it shows up in my IOS Smartthings App but simply does not respond to siwtching relays. Throught the web interface I can switch the relays though ... Thanks for your great code and project !!!

**Comment by JZ-SmartThings** [comment]
NP, my guess is you're using the default of POST method originally for PHP code but any of the Arduino code consumers need GET instead.

FYI, don't modify any of the code. No need to do that, in SmartThings just click the cog/gear on top and modify those settings via UI, not the code. Enjoy, closing the bug, please post feedback to ST forum, just easier for me to deal with :)
